//* Login
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LIMPIAR_USER = "LIMPIAR_USER";

//* Publicaciones
export const GET_ANUNCIOS = "GET_ANUNCIOS";
export const LIMPIAR_ANUNCIOS = "LIMPIAR_ANUNCIOS";
export const ERROR_ANUNCIO = "ERROR_ANUNCIO";
export const AGREGAR_ANUNCIO = "AGREGAR_ANUNCIO";
export const ELIMINAR_PUBLICACION = "ELIMINAR_PUBLICACION";
